CREATE DATABASE GarageVParrot;
 
USE DATABASE GarageVParrot;

CREATE TABLE users(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, 
last_name VARCHAR(100) NOT NULL, first_name VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON(50) NOT NULL);

CREATE TABLE car(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, car_name VARCHAR(255) NOT NULL, 
price DOUBLE NOT NULL, year DATE NOT NULL, kilometers INTEGER NOT NULL, manufacturer VARCHAR(255) NOT NULL, characteristic LONGTEXT NOT NULL);

CREATE TABLE review(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, review_name VARCHAR(255) NOT NULL, 
rating INTEGER NOT NULL, content LONGTEXT NOT NULL);

ALTER TABLE review ADD approved TINYINT(1) NOT NULL;

CREATE TABLE services(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL);

CREATE TABLE contact(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, last_name VARCHAR(100) NOT NULL, 
first_name VARCHAR(100) NOT NULL, phone_number VARCHAR(15) NOT NULL, email VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL);

ALTER TABLE contact ADD processed TINYINT(1) NOT NULL;

CREATE TABLE schedule(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, days VARCHAR(50) NOT NULL, opening_hour VARCHAR(100) NOT NULL);

CREATE TABLE image(id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL, car_id NOT NULL, image_name VARCHAR(255) NOT NULL, image_size INTEGER NOT NULL);
ALTER TABLE image ADD FOREIGN KEY (car_id) REFERENCES car(id);

ALTER TABLE car ADD fuel VARCHAR(255) NOT NULL;
ALTER TABLE car ADD photo VARCHAR(255) NOT NULL;

ALTER TABLE car DROP photo;
ALTER TABLE car MODIFY year VARCHAR(255) NOT NULL;
ALTER TABLE image ADD updated_at DATETIME NULL;

ALTER TABLE car ADD contact_id NULL;
ALTER TABLE car ADD FOREIGN KEY (contact_id) REFERENCES contact(id);

ALTER TABLE review ADD last_name VARCHAR(255) NOT NULL;

ALTER TABLE services ADD image_name VARCHAR(255) NULL;
ALTER TABLE services ADD updated_at DATETIME NULL;




